#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 3 5 7
bspc monitor DisplayPort-1 -d 2 4 6 8 

bspc config border_width        2
bspc config window_gap          4
bspc config top_padding		30
bspc config bottom_padding	6
bspc config left_padding	6
bspc config right_padding	6
bspc config split_ratio		0.52
bspc config single_monocle	false
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config poitner_follows_focus true
bspc config pointer_modifier 	mod4
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#Colors
#bspc config
#bspc config
#bspc config
#bspc config
