#!/bin/bash

#---autostart---#
xrandr -s 1440x900
~/.config/polybar/launch.sh &
killall "nm-applet"
nm-applet &
sxhkd &
picom &
variety --no-startup-id &

#---workspaces---#
bspc monitor Virtual-1 -d 1 2 3 4 5 6 7 8 9

#---window settings---#
bspc config border_width        0
bspc config window_gap          12
bspc config top_padding		2
bspc config bottom_padding	12
bspc config left_padding	12
bspc config right_padding	12

#---tree settings---#
bspc config automatic_scheme spiral
bspc config intial_polarity second_child

#---disabled settings (may use later)---#
#bspc config removal_adjustment  true
#bspc config borderless monocle  true
#bspc config gapless_monocle	false

#---misc settings---#
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config center_pseudo_tiled		true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config split_ratio          0.5
